### ISSUE TITLE
Create a callback to remove all notifications from the screen

### ISSUE THREAD

**Issue by Tudumanu** [ralivue/jquery-notific8#34]
It would be nice to a callback to remove all notific8 from the screen

**Comment by Tudumanu** [comment]
I am using this way:
```
$('.jquery-notific8-notification').remove();
```

**Comment by willsteinmetz** [comment]
Is this for just the visible notifications or for the plug-in overall?

**Comment by Tudumanu** [comment]
Visible only

**Comment by willsteinmetz** [comment]
A new function called remove will remove all visible notifications on the screen instantly while leaving the plug-in's foot print. It can be called with `$.notific8('remove');`.

The destroy function has also been completed. That will remove all of the notifications and the plug-in's foot print. It can be called with `$.notific8('destroy');`.
